version: '3.9'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 service_name

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
    volumes:
      - $PWD/database:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
     - app-tier

  python_app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-tier
    command:
      tail -f /dev/null
    volumes:
      - .:/usr/src/app # Makes requests work for some reason

networks:
  app-tier:
    driver: bridge
